import streamlit as st
import requests
import json
from datetime import datetime
import time
import os
import subprocess
import sys
from pathlib import Path

# Page configuration
st.set_page_config(
    page_title="Unsubscribe Email Workflow",
    page_icon="📧",
    layout="wide",
    initial_sidebar_state="expanded"
)

# API base URL
API_BASE_URL = "http://localhost:8000"

# Email account configurations
EMAIL_ACCOUNTS = {
    "Cloudchillies (Rediff)": {
        "provider": "rediff",
        "host": "imap.rediffmailpro.com",
        "port": 993,
        "email_placeholder": "user1@cloudchillies.com"
    },
    "Lending Logic (Microsoft 365)": {
        "provider": "outlook",
        "host": "outlook.office365.com",
        "port": 993,
        "email_placeholder": "user2@lendinglogic.com"
    },
    "Gmail": {
        "provider": "gmail",
        "host": "imap.gmail.com",
        "port": 993,
        "email_placeholder": "user@gmail.com"
    }
}

LLM_PROVIDERS = {
    "Ollama (Local)": {
        "provider": "ollama",
        "model": "llama3.2:latest",
        "description": "Local LLM via Ollama"
    },
    "Gemini (Cloud)": {
        "provider": "gemini",
        "model": "gemini-2.0-flash-exp",
        "description": "Google Gemini AI"
    }
}


def load_env_file():
    """Load current .env file"""
    env_path = Path(".env")
    env_vars = {}
    
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key.strip()] = value.strip()
    
    return env_vars


def save_env_file(env_vars):
    """Save updated .env file"""
    env_path = Path(".env")
    
    with open(env_path, 'w') as f:
        f.write("# Unsubscribe Email Workflow Configuration\n")
        f.write("# Generated by Streamlit UI\n\n")
        
        f.write("# Brevo API\n")
        f.write(f"BREVO_API_KEY={env_vars.get('BREVO_API_KEY', '')}\n\n")
        
        f.write("# LLM Configuration\n")
        f.write(f"LLM_PROVIDER={env_vars.get('LLM_PROVIDER', 'gemini')}\n")
        f.write(f"OLLAMA_MODEL={env_vars.get('OLLAMA_MODEL', 'llama3.2:latest')}\n")
        f.write(f"OLLAMA_BASE_URL={env_vars.get('OLLAMA_BASE_URL', 'http://localhost:11434')}\n")
        f.write(f"GEMINI_API_KEY={env_vars.get('GEMINI_API_KEY', '')}\n")
        f.write(f"GEMINI_MODEL={env_vars.get('GEMINI_MODEL', 'gemini-2.0-flash-exp')}\n\n")
        
        f.write("# IMAP Configuration\n")
        f.write(f"IMAP_ENABLED={env_vars.get('IMAP_ENABLED', 'false')}\n")
        f.write(f"IMAP_PROVIDER={env_vars.get('IMAP_PROVIDER', 'outlook')}\n")
        f.write(f"IMAP_HOST={env_vars.get('IMAP_HOST', '')}\n")
        f.write(f"IMAP_PORT={env_vars.get('IMAP_PORT', '993')}\n")
        f.write(f"IMAP_EMAIL={env_vars.get('IMAP_EMAIL', '')}\n")
        f.write(f"IMAP_PASSWORD={env_vars.get('IMAP_PASSWORD', '')}\n")
        f.write(f"IMAP_FOLDER={env_vars.get('IMAP_FOLDER', 'INBOX')}\n")
        f.write(f"IMAP_CHECK_INTERVAL={env_vars.get('IMAP_CHECK_INTERVAL', '3600')}\n")


def check_api_health():
    """Check if API is running"""
    try:
        response = requests.get(f"{API_BASE_URL}/health", timeout=2)
        return response.status_code == 200, response.json()
    except Exception as e:
        return False, {"error": str(e)}


def get_worker_status():
    """Get worker status from API"""
    try:
        response = requests.get(f"{API_BASE_URL}/worker/status", timeout=2)
        if response.status_code == 200:
            return response.json()
        return None
    except:
        return None


def test_brevo_api(email):
    """Test Brevo API"""
    try:
        response = requests.post(
            f"{API_BASE_URL}/test-brevo",
            json={"email": email},
            timeout=10
        )
        return response.status_code, response.json()
    except Exception as e:
        return 500, {"error": str(e)}


def test_intent_detection(message_text, sender_email="test@example.com"):
    """Test intent detection"""
    try:
        response = requests.post(
            f"{API_BASE_URL}/test-intent",
            json={"message_text": message_text, "sender_email": sender_email},
            timeout=30
        )
        return response.status_code, response.json()
    except Exception as e:
        return 500, {"error": str(e)}


def trigger_check_now():
    """Trigger immediate email check"""
    try:
        response = requests.post(f"{API_BASE_URL}/worker/check-now", timeout=60)
        return response.status_code, response.json()
    except Exception as e:
        return 500, {"error": str(e)}


def restart_api():
    """Restart the API server"""
    try:
        # Try to shutdown the current server
        try:
            requests.post(f"{API_BASE_URL}/shutdown", timeout=2)
        except:
            pass
        
        time.sleep(2)
        
        # Start new server process
        venv_python = Path("venv/Scripts/python.exe")
        if venv_python.exists():
            subprocess.Popen(
                [str(venv_python), "main.py"],
                cwd=os.getcwd(),
                creationflags=subprocess.CREATE_NEW_CONSOLE if sys.platform == 'win32' else 0
            )
            return True, "API server restart initiated"
        else:
            return False, "Virtual environment not found"
    except Exception as e:
        return False, f"Error restarting API: {str(e)}"


# Sidebar - Configuration
with st.sidebar:
    st.title("⚙️ Configuration")
    
    # Check API status
    api_healthy, health_data = check_api_health()
    
    if api_healthy:
        st.success("✅ API Running")
        if 'services' in health_data:
            worker = health_data['services'].get('email_worker', {})
            if worker.get('running'):
                st.info(f"🔄 Worker Active")
            else:
                st.warning(f"⏸️ Worker Disabled")
    else:
        st.error("❌ API Not Running")
        st.caption("Run: `python main.py`")
    
    st.divider()
    
    # Load current config
    current_env = load_env_file()
    
    st.subheader("📧 Email Account")
    
    selected_account = st.selectbox(
        "Select Account",
        options=list(EMAIL_ACCOUNTS.keys()),
        help="Choose which email account to monitor"
    )
    
    account_config = EMAIL_ACCOUNTS[selected_account]
    
    with st.expander("Email Settings", expanded=True):
        imap_enabled = st.toggle(
            "Enable IMAP Worker",
            value=current_env.get('IMAP_ENABLED', 'false').lower() == 'true',
            help="Enable hourly email checking"
        )
        
        imap_email = st.text_input(
            "Email Address",
            value=current_env.get('IMAP_EMAIL', ''),
            placeholder=account_config['email_placeholder']
        )
        
        imap_password = st.text_input(
            "Password / App Password",
            value=current_env.get('IMAP_PASSWORD', ''),
            type="password",
            help="Use App Password for Gmail/Outlook"
        )
        
        check_interval = st.number_input(
            "Check Interval (seconds)",
            min_value=60,
            max_value=86400,
            value=int(current_env.get('IMAP_CHECK_INTERVAL', '3600')),
            step=300,
            help="How often to check for new emails"
        )
    
    st.divider()
    
    st.subheader("🤖 LLM Provider")
    
    selected_llm = st.selectbox(
        "Select LLM",
        options=list(LLM_PROVIDERS.keys()),
        index=0 if current_env.get('LLM_PROVIDER', 'gemini') == 'ollama' else 1
    )
    
    llm_config = LLM_PROVIDERS[selected_llm]
    
    with st.expander("LLM Settings", expanded=True):
        if llm_config['provider'] == 'ollama':
            ollama_url = st.text_input(
                "Ollama Base URL",
                value=current_env.get('OLLAMA_BASE_URL', 'http://localhost:11434')
            )
            ollama_model = st.text_input(
                "Model Name",
                value=current_env.get('OLLAMA_MODEL', 'llama3.2:latest')
            )
        else:
            gemini_api_key = st.text_input(
                "Gemini API Key",
                value=current_env.get('GEMINI_API_KEY', ''),
                type="password"
            )
            gemini_model = st.text_input(
                "Model Name",
                value=current_env.get('GEMINI_MODEL', 'gemini-2.0-flash-exp')
            )
    
    st.divider()
    
    st.subheader("🔑 Brevo API")
    
    brevo_api_key = st.text_input(
        "Brevo API Key",
        value=current_env.get('BREVO_API_KEY', ''),
        type="password"
    )
    
    st.divider()
    
    # Save configuration
    if st.button("💾 Save Configuration", type="primary", use_container_width=True):
        new_env = {
            'BREVO_API_KEY': brevo_api_key,
            'LLM_PROVIDER': llm_config['provider'],
            'OLLAMA_MODEL': current_env.get('OLLAMA_MODEL', 'llama3.2:latest'),
            'OLLAMA_BASE_URL': current_env.get('OLLAMA_BASE_URL', 'http://localhost:11434'),
            'GEMINI_API_KEY': current_env.get('GEMINI_API_KEY', ''),
            'GEMINI_MODEL': current_env.get('GEMINI_MODEL', 'gemini-2.0-flash-exp'),
            'IMAP_ENABLED': 'true' if imap_enabled else 'false',
            'IMAP_PROVIDER': account_config['provider'],
            'IMAP_HOST': account_config['host'],
            'IMAP_PORT': str(account_config['port']),
            'IMAP_EMAIL': imap_email,
            'IMAP_PASSWORD': imap_password,
            'IMAP_FOLDER': 'INBOX',
            'IMAP_CHECK_INTERVAL': str(check_interval)
        }
        
        if llm_config['provider'] == 'ollama':
            new_env['OLLAMA_BASE_URL'] = ollama_url
            new_env['OLLAMA_MODEL'] = ollama_model
        else:
            new_env['GEMINI_API_KEY'] = gemini_api_key
            new_env['GEMINI_MODEL'] = gemini_model
        
        save_env_file(new_env)
        st.success("✅ Configuration saved!")
        st.session_state['config_saved'] = True
    
    # Show restart button if config was saved
    if st.session_state.get('config_saved', False):
        st.divider()
        st.warning("⚠️ Configuration changed - Restart required!")
        
        col1, col2 = st.columns(2)
        
        with col1:
            if st.button("🔄 Auto Restart API", use_container_width=True):
                with st.spinner("Restarting API server..."):
                    success, message = restart_api()
                    
                    if success:
                        st.success(f"✅ {message}")
                        st.info("⏳ Waiting for API to start...")
                        
                        # Wait for API to be ready
                        for i in range(10):
                            time.sleep(2)
                            healthy, _ = check_api_health()
                            if healthy:
                                st.success("✅ API is running!")
                                st.session_state['config_saved'] = False
                                st.rerun()
                                break
                        else:
                            st.warning("⏳ API starting (may take a moment)")
                    else:
                        st.error(f"❌ {message}")
        
        with col2:
            if st.button("📝 Manual Restart", use_container_width=True):
                st.info("""
                **Manual restart steps:**
                1. Stop current API (Ctrl+C in terminal)
                2. Run: `python main.py`
                """)
                if st.button("✅ Done - Clear Alert"):
                    st.session_state['config_saved'] = False
                    st.rerun()


# Main content
st.title("📧 Unsubscribe Email Workflow")
st.caption("Automated email unsubscribe processing with LLM intent detection")

# Create tabs
tab1, tab2, tab3, tab4 = st.tabs(["📊 Dashboard", "🧪 Test Intent", "✉️ Test Brevo", "📝 Logs"])

# Tab 1: Dashboard
with tab1:
    col1, col2, col3 = st.columns(3)
    
    with col1:
        st.metric("API Status", "Running" if api_healthy else "Offline", 
                 delta="Healthy" if api_healthy else "Check connection")
    
    with col2:
        worker_status = get_worker_status()
        if worker_status and worker_status.get('running'):
            st.metric("Worker Status", "Active", delta="Running")
        else:
            st.metric("Worker Status", "Disabled", delta="Not running")
    
    with col3:
        if api_healthy and 'config' in health_data:
            llm = health_data['config'].get('llm_provider', 'N/A')
            st.metric("LLM Provider", llm.title(), delta="Configured")
        else:
            st.metric("LLM Provider", "N/A", delta="Check config")
    
    st.divider()
    
    # Worker details
    if worker_status:
        st.subheader("🔄 Worker Details")
        
        col1, col2 = st.columns(2)
        
        with col1:
            st.info(f"""
            **Status:** {'🟢 Running' if worker_status.get('running') else '🔴 Stopped'}
            
            **Next Check:** {worker_status.get('next_run_time', 'N/A')}
            
            **Check Interval:** {worker_status.get('check_interval', 'N/A')} seconds
            """)
        
        with col2:
            if st.button("🔄 Check Emails Now", use_container_width=True):
                with st.spinner("Checking emails..."):
                    status_code, result = trigger_check_now()
                    
                    if status_code == 200:
                        st.success("✅ Email check completed!")
                        st.json(result)
                    else:
                        st.error(f"❌ Error: {result}")
    else:
        st.info("ℹ️ Worker is disabled. Enable it in the sidebar configuration.")
    
    st.divider()
    
    # System info
    if api_healthy:
        st.subheader("⚙️ System Information")
        
        with st.expander("View Details", expanded=False):
            st.json(health_data)

# Tab 2: Test Intent Detection
with tab2:
    st.subheader("🧪 Test Intent Detection")
    st.caption("Test the LLM's ability to detect unsubscribe intent")
    
    # Sample messages
    sample_messages = {
        "Unsubscribe Request": "Please unsubscribe me from your mailing list. I no longer wish to receive these emails.",
        "Stop Emails": "Stop sending me these promotional emails immediately!",
        "Regular Email": "Thank you for your email. I'm interested in learning more about your product.",
        "Question": "Hi, I have a question about my recent order. Can you help?",
        "Complaint": "I'm not satisfied with your service and want a refund."
    }
    
    col1, col2 = st.columns([1, 1])
    
    with col1:
        selected_sample = st.selectbox(
            "Select Sample Message",
            options=["Custom"] + list(sample_messages.keys())
        )
    
    with col2:
        sender_email = st.text_input(
            "Sender Email (Optional)",
            value="test@example.com",
            placeholder="sender@example.com",
            help="Email address of the sender (for testing purposes)"
        )
    
    message_text = st.text_area(
        "Email Message",
        value=sample_messages.get(selected_sample, "") if selected_sample != "Custom" else "",
        height=150,
        placeholder="Enter email message text to analyze..."
    )
    
    if st.button("🤖 Analyze Intent", type="primary"):
        if message_text.strip():
            with st.spinner("Analyzing with LLM..."):
                status_code, result = test_intent_detection(message_text, sender_email)
                
                if status_code == 200:
                    intent = result.get('has_unsubscribe_intent', False)
                    confidence = result.get('confidence', 'unknown')
                    reasoning = result.get('reasoning', 'No reasoning provided')
                    
                    if intent:
                        st.success("✅ Unsubscribe Intent Detected!")
                    else:
                        st.info("ℹ️ No Unsubscribe Intent Detected")
                    
                    col1, col2 = st.columns(2)
                    with col1:
                        st.metric("Intent", "Yes" if intent else "No")
                    with col2:
                        st.metric("Confidence", confidence.title())
                    
                    st.subheader("💭 Reasoning")
                    st.write(reasoning)
                else:
                    st.error(f"❌ Error: {result}")
        else:
            st.warning("⚠️ Please enter a message to analyze")

# Tab 3: Test Brevo API
with tab3:
    st.subheader("✉️ Test Brevo API")
    st.caption("Test blacklisting an email address in Brevo")
    
    test_email = st.text_input(
        "Email to Blacklist",
        placeholder="test@example.com",
        help="This will actually blacklist the email in Brevo"
    )
    
    st.warning("⚠️ This will actually blacklist the email in your Brevo account!")
    
    if st.button("🚫 Blacklist Email", type="primary"):
        if test_email:
            with st.spinner("Blacklisting email in Brevo..."):
                status_code, result = test_brevo_api(test_email)
                
                if status_code == 200 and result.get('success'):
                    st.success(f"✅ {result.get('message', 'Success')}")
                    st.json(result)
                else:
                    st.error(f"❌ Error: {result}")
        else:
            st.warning("⚠️ Please enter an email address")

# Tab 4: Activity Logs
with tab4:
    st.subheader("📝 Activity Logs")
    st.caption("View recent activity (requires log file)")
    
    st.info("ℹ️ Log viewing feature - Coming soon!")
    st.caption("For now, check the terminal where `python main.py` is running")


# Footer
st.divider()
col1, col2, col3 = st.columns(3)

with col1:
    st.caption(f"🕐 Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

with col2:
    if st.button("🔄 Refresh", use_container_width=True):
        st.rerun()

with col3:
    st.caption("Made with ❤️ using Streamlit")
